### ISSUE TITLE
Error when trying to extract zip file

### ISSUE THREAD

**Issue by chrisCayanan** [NikolayXHD/Mtgdb#18]
![error](https://user-images.githubusercontent.com/37635490/38902415-6b928744-426e-11e8-90c0-06dc691da156.png)

I receive this error when trying to extract files from the zipped folder.

**Comment by NikolayXHD** [comment]
I downloaded Mtgdb.Gui.v3.5.0.4.zip from https://goo.gl/LuC6ce and succesfully unzipped it.
Did you download from the same url?

When extracting .zip what was target directory? 
From the screenshot it appears to be the desktop. If so, try to unzip to a different directory e.g. c:\games\mtgdb.gui

When extracting .zip was target directory empty?

**Comment by NikolayXHD** [comment]
no feedback

**Comment by michachu** [comment]
Hi, I have this same error. I've tried unzipping it to a different directory, but to no avail. It seems like there is an error with the file?

**Comment by NikolayXHD** [comment]
Hi, I think you are probably using default Windows zip file manager. Mtgdb.Gui.zip is compressed using advanced .zip compression method which default windows zip file manager cannot handle.

You can use for instance [7-zip](https://www.7-zip.org/) to extract it.
