### ISSUE TITLE
Change image repository

### ISSUE THREAD

**Issue by rafaelfcponde** [NikolayXHD/Mtgdb#3]
Having the images in Mega can be quite annoying, as "bandwith limit" is a thing.

**Comment by NikolayXHD** [comment]
Would you suggest an alternative hosting?

**Comment by rafaelfcponde** [comment]
I don't know any, unfortunately

**Comment by NikolayXHD** [comment]
If one day I happen to hear about a free online file storage without bandwidth limitation I will consider making Mtgdb.Gui use images from that storage.

As for now the issue cannot be fixed as it requires further research.

**Comment by NikolayXHD** [comment]
Migrated images to Google drive
