### ISSUE TITLE
Don't ship pdb files

### ISSUE THREAD

**Issue by liberforce** [NikolayXHD/Mtgdb#30]
Never used your app (and will probably never use it as it's Windows-only, that's the "like:" feature that brought it to my attention), but I downloaded it, and browsed through the directories. You ship pdb files, and this only makes sense for developers, not users, so unless you target a developer audience, you should probably not ship them in your releases.

**Comment by NikolayXHD** [comment]
Ihanks for the tip, it will also save a couple of MB in downloadable .zip at no cost

**Comment by NikolayXHD** [comment]
done
