### ISSUE TITLE
Linux version? [Feature Request]

### ISSUE THREAD

**Issue by The1AndMany** [NikolayXHD/Mtgdb#55]
Feature request
===============

I've been looking for a program that can give me a list of decks I can build with just cards I own, and this program *almost* seems to fit the bill. The only issue is that I run Linux. Is there any way Linux support can be added? Even just being able to build a linux binary from source would be great...

**Comment by NikolayXHD** [comment]
The funny thing is I am also Linux user, so I tried porting to linux for my own sake, like a year ago.

The thing that prevented success, when everything else was more or less working, was .NET charts being not implemented in Mono.

Mtgdb.Gui uses charts for mana curve and other graphs which are handy to analyze deck / collection.

It means I have to use another Charts library, compatible with mono, and doing so requires a significant effort, at least 1 person-week I guess, so I gave up at that moment.

**Comment by TeamLinux01** [comment]
I would love to see this ported to Linux as well.
I think it is one of the best applications for deck building and I would like to start tracking my very large collection.

If you to get it ported someday, please create a Flatpak version and post it on flathub (https://flathub.org).

**Comment by TeamLinux01** [comment]
I have been wondering, could the app be built using .NET core (https://dotnet.microsoft.com/download)?
What is the point of Microsoft open-sourcing parts of .NET if it isn't usable to build apps with?

If .NET Core isn't viable, I can see why mono is still around.

**Comment by NikolayXHD** [comment]
A usable Mono-compatible version is ready, what is left is a little infrastructure work, mostly use searate URL's for release and auto-update purposes. A downloadable will be ready in a couple of days.


> If .NET Core isn't viable, I can see why mono is still around.

.NET Core is not viable for cross-platform desktop applications AFAIK, still viable for web services.

> If you to get it ported someday, please create a Flatpak version and post it on flathub (https://flathub.org).

Thanks for the tip! That would be great to have application release and update set-up in a proper linux way.

**Comment by NikolayXHD** [comment]
done, v4.1.0.0 can be run in Linux with Mono

Turs out, I don't need to build / release linux version separately, Mono runs original executables just fine -> no extra maintenance work for me.
