### ISSUE TITLE
Add multiple cards to collections

### ISSUE THREAD

**Issue by pedrohasselmann** [NikolayXHD/Mtgdb#56]
Feature request
===============

description, importance statement
---------------------------------

Dear Nikolay,

Is there a way to add multiple cards to my collection with a single command?
I often buy commons and uncommon sets of a given collection to draft singleton decks, and it would be much easier if I could select a full expansion directly to my collections.

Thanks for your great work here! You have truly the best mtg manager here.

**Comment by NikolayXHD** [comment]
Hello, @pedrohasselmann, sorry for an extremely delayed response.

I believe the functionality you want is currently half-available. There is a button `Add to Collection from Clipboard`

![screenshot](https://github.com/NikolayXHD/Mtgdb/raw/master/out/help/l/chart-paste-collection.jpg)

The question would be how to put the cards you need to the Clipboard. I suggest adding another clipboard operation button `Copy search result to clipboard`.

The flow would be the following:

1. Filter to the set you want using `Search bar`. The query would become like `SetCode: ISD`
2. Narrow down the search result to the cards you want to add e.g. exactly 1 copy.
2.1 Get the card names that need to be excluded to `Search bar` by clicking on [Search button over card name field](https://github.com/NikolayXHD/Mtgdb/wiki/4.1-Search-button-over-card-text) The query becomes `SetCode: ISD NameEn: "some name"`
2.2 Edit the query to exclude the card, add `AND NOT` operator, so the query becomes `SetCode: ISD AND NOT NameEn: "card name"`
3. `Copy search result to clipboard` - 1 copy of any card in search result is added to clipboard
4. `Add to collection from Clipboard` 1 time
2'.  Narrow down the search result to the cards which you want to add exactly 2 copies
3'. `Copy search result to clipboard`
4'. `Add to collection from Clipboard` 2 times
...

The solution above requires only a little work from me, so as soon as we agree on it or something as easy as it, I will add it to Mtgdb.Gui and release new version within 1 day.

**Comment by NikolayXHD** [comment]
done in 4.0.7.6
