### ISSUE TITLE
Problems launching Linux start.sh

### ISSUE THREAD

**Issue by TeamLinux01** [NikolayXHD/Mtgdb#58]
Bug report
==========

Mtgdb.Gui version
-----------------
4.1.0.0

Steps to reproduce the bug
--------------------------
Download the zip file on Linux (Pop!_OS 20.04)
unzip the file
change directory to the extracted files
terminal command `chmod ug+x start.sh`
terminal command `./start.sh`

Actual result (the bug)
-----------------------
Output error:
"Failed to execute process './start.sh'. Reason:
exec: Exec format error
The file './start.sh' is marked as an executable but could not be run by the operating system."

Expected result
---------------
Launch the program or come up with an error saying mono needs to be installed.

Feature request
===============

description, importance statement
---------------------------------

suggested solution
------------------
If I copy the text into a newly created .sh file and mark that as executable, it runs just fine. It could be a problem if the file is created on Windows, that it has some hidden bits that are confusing the interpreter.

**Comment by NikolayXHD** [comment]
That's right, it was unicode byte order mark, thank you
