### ISSUE TITLE
Release on Flathub as a flatpak

### ISSUE THREAD

**Issue by TeamLinux01** [NikolayXHD/Mtgdb#59]
Bug report
==========

Mtgdb.Gui version
-----------------

Steps to reproduce the bug
--------------------------

Actual result (the bug)
-----------------------

Expected result
---------------

Feature request
===============
Package program as a flatpak on Linux, release on Flathub.

description, importance statement
---------------------------------
Make it easy and accessible for Linux users.
Flatpaks are sandboxed and include their dependencies, so the software and dependencies can be automatically downloaded and installed.

Flatpak developer guide: https://docs.flatpak.org/en/latest/

suggested solution
------------------

P.S. Thank you very much for all the hard work you have put into this application.

**Comment by NikolayXHD** [comment]
I had a look of what would it take to have a flatpak package for Mtgdb.Gui. From what I can see, there is currently no good way to achieve that, see explanation below.

Mtgdb.Gui in GNU/Linux requires Mono.NET to run. Mono is big and there is currently no available runtime supporting it out of the box ([list of available runtimes](https://docs.flatpak.org/en/latest/available-runtimes.html). 

In such cases the proper way to reference it would be the [Base App approach](https://docs.flatpak.org/en/latest/dependencies.html#base-apps), such as [Electron base app](https://github.com/flathub/io.atom.electron.BaseApp). But then again, there is no Mono.NET base app available at the moment ([search result](https://github.com/search?q=org%3Aflathub+baseapp&unscoped_q=baseapp)).

One could still [bundle](https://docs.flatpak.org/en/latest/dependencies.html#bundling) Mono runtime with the package, but considering the size of Mono, I don't think it's a good solution.

Considering above I am closing the issue for now. Feel free to reopen it I've missed something. I'll be monitoring the news regarding Mono.NET and flatpak in case the situation changes for the better.

**Comment by TeamLinux01** [comment]
It seems you are correct.
I hope this Google Summer of Code gets approved and completed. https://www.mono-project.com/community/google-summer-of-code/projects/#flatpak-support-for-mono-apps
