### ISSUE TITLE
Release a Linux AppImage

### ISSUE THREAD

**Issue by TeamLinux01** [NikolayXHD/Mtgdb#60]
Bug report
==========

Mtgdb.Gui version
-----------------

Steps to reproduce the bug
--------------------------

Actual result (the bug)
-----------------------

Expected result
---------------

Feature request
===============

description, importance statement
---------------------------------

Possibly an easier way to support Linux users.

suggested solution
------------------

Look into packaging the application up as an AppImage, that way the AppImage can be executed to launch the GUI app, instead of having to extract all the files and run start.sh in a terminal.
https://docs.appimage.org/packaging-guide/index.html

As an example of another application that uses mono that ships an AppImage, maybe take a look at OpenRA's github with this issue (Bundle Mono inside AppImage): https://github.com/OpenRA/OpenRA/issues/15965
Not bundling Mono is fine with me, just having it request it needing to be downloaded and installed is OK.

Thank you for taking my suggestions into consideration and I appreciate your hard work making and maintaining Mtgdb.Gui.

**Comment by NikolayXHD** [comment]
I want to thank you in return for your suggestions to be concrete and easy to follow. Also, being novice in Linux I found following your tip beneficial for my literacy.

Will see about AppImage the coming weekend.

**Comment by probonopd** [comment]
If you need some help, I know everything about AppImage but practically nothing about Mono...

**Comment by NikolayXHD** [comment]
AppImage requires that MyApp does not touch the application directory - when AppImage gets mounted, it is a temporary read-only mount point. I find it 100% reasonable, but currently Mtgdb.Gui does a many different things that result in writes to app directory, including self-update.

Probably any reasonable packaging system require or suggest a similar approach, so this needs to be fixed. This the issue is becoming long term.

**Comment by TeamLinux01** [comment]
I was thinking that if the program is made to be AppImage friendly, then it could probably also be bundled better as a Windows portable executable instead of a zip file.
If I find some good documentation on how to make a read-only, self-contained .NET compiled executable, I will more than likely open another issue to help with that tracking.

If I can help out in other ways, please let me know.
